[package]
name = "bake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "bake"
path = "./main.rs"

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
nom = "7.1.3"
